version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/keys:/app/keys
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://myuser:mypass@db:5432/mydb
      - FIREBASE_KEY_PATH=/app/keys/firebaseKey.json

volumes:
  pgdata:
