version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/keys:/app/keys
    env_file:
      - ./backend/.env.test
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./frontend/nginx.dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  e2e-tests:
    build:
      context: ./e2e
      dockerfile: Dockerfile
    volumes:
      - ./e2e:/app
      - ./backend/.env.test:/app/.env.test
    depends_on:
      frontend:
        condition: service_healthy
      backend:
        condition: service_healthy
    command: ["npm", "run", "test:docker"]
    environment:
      - CI=true
