version: "3.7"

services:
  backend:
    image: amimulamim/studybuddy-backend:latest
    expose:
      - "8000"
    volumes:
      - ./firebaseKey.json:/app/keys/firebaseKey.json
    env_file:
      - ./.env

  frontend:
    image: amimulamim/studybuddy-frontend:latest
    
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro

    depends_on:
      - backend
