version: "3.9"

services:
  app:
    build:
      context: .
    image: studybuddyimagecontainer.azurecr.io/backend:latest
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - .env.test
    volumes:
      - ./.env:/app/.env:ro                # Mount `.env` file into container root
      - ./keys:/app/keys:ro

  test:
    build:
      context: .
    image: studybuddyimagecontainer.azurecr.io/backend:latest
    depends_on:
      - app
    env_file:
      - .env.test
    command: >
      sh -c "sleep 5; coverage run -m pytest; coverage report; coverage xml;
      sed -i 's|<source>app</source>|<source>backend/app</source>|' coverage_reports/coverage.xml"
    volumes:
      - .:/app
      - ./.env:/app/.env:ro
      - ./keys:/app/keys:ro
