openapi: 3.0.3
info:
  title: StudyBuddy API
  version: 1.0.0
  description: API docs for StudyBuddy modules
servers:
- url: http://localhost:8000
tags:
- name: Auth
- name: Chat
- name: Billing
  description: Subscription and payment management
- name: ResourceProcessing
  description: Document processing ,parsing and vectorization
paths:
  /resource/upload:
    post:
      tags:
      - ResourceProcessing
      summary: Upload a resource document (PDF)
      description: 'Uploads a PDF document. System automatically parses text, images,
        tables,

        chunks the text, vectorizes the content, and stores embeddings internally.

        '
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: PDF document file to upload
      responses:
        '200':
          description: Upload and processing completed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  documentId:
                    type: string
                  processingStatus:
                    type: string
                    example: Completed
                  summary:
                    type: object
                    properties:
                      textExtracted:
                        type: boolean
                      imagesExtracted:
                        type: boolean
                      tablesExtracted:
                        type: boolean
        '400':
          description: Upload failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /api/auth/signup:
    post:
      tags:
      - Auth
      summary: Sign up using email and password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - email
              - password
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
      responses:
        '201':
          description: User created
        '400':
          description: Invalid input
  /api/auth/login:
    post:
      tags:
      - Auth
      summary: Log in using email and password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - email
              - password
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
      responses:
        '200':
          description: Login successful
        '401':
          description: Unauthorized
  /api/auth/google:
    post:
      tags:
      - Auth
      summary: Google Sign-in
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - idToken
              properties:
                idToken:
                  type: string
      responses:
        '200':
          description: Google login/signup handled
        '401':
          description: Invalid token
  /api/auth/user-info:
    get:
      tags:
      - Auth
      summary: Get user info
      security:
      - bearerAuth: []
      responses:
        '200':
          description: User profile
        '401':
          description: Unauthorized
  /billing/subscribe:
    post:
      tags:
      - Billing
      summary: Create a checkout session to subscribe to premium plan
      description: 'Redirects the user to the payment provider (e.g., Stripe) to complete
        the checkout.

        '
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                planId:
                  type: string
                  example: premium_monthly
                successUrl:
                  type: string
                cancelUrl:
                  type: string
      responses:
        '200':
          description: Checkout session created
          content:
            application/json:
              schema:
                type: object
                properties:
                  checkoutUrl:
                    type: string
                    description: Redirect URL to complete payment
        '400':
          description: Invalid request
  /billing/status:
    get:
      tags:
      - Billing
      summary: Check the user's current subscription status
      security:
      - bearerAuth: []
      responses:
        '200':
          description: Subscription status details
          content:
            application/json:
              schema:
                type: object
                properties:
                  plan:
                    type: string
                    enum:
                    - free
                    - premium
                  active:
                    type: boolean
                  expiresAt:
                    type: string
                    format: date-time
  /billing/cancel:
    post:
      tags:
      - Billing
      summary: Cancel the current user's subscription
      security:
      - bearerAuth: []
      responses:
        '200':
          description: Subscription cancellation confirmed
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /billing/webhook:
    post:
      tags:
      - Billing
      summary: Handle incoming payment gateway webhooks
      description: 'Receives events from payment providers like Stripe. This endpoint
        is **internal** and should be secured with a secret key.

        '
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties: true
      responses:
        '200':
          description: Webhook processed
  /ai/chat:
    post:
      tags:
      - Chat
      summary: Start or continue a chat with AI
      description: 'Starts a new chat session if `chatId` is not provided.

        If `chatId` is provided, the message is added to the existing session.

        '
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                text:
                  type: string
                  description: User's message text
                image:
                  type: string
                  format: binary
                  description: Optional image file
                chatId:
                  type: string
                  description: Optional chat session ID
      responses:
        '200':
          description: AI responded successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  chatId:
                    type: string
                  messages:
                    type: array
                    items:
                      $ref: '#/components/schemas/Message'
        '400':
          description: Invalid input (e.g., no message, multiple files, file too large)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '401':
          description: Unauthorized (missing or invalid token)
        '413':
          description: Payload too large (file size exceeded)
  /ai/chat/list:
    get:
      tags:
      - Chat
      summary: Get list of all chat sessions for the user
      security:
      - bearerAuth: []
      responses:
        '200':
          description: List of chat sessions
          content:
            application/json:
              schema:
                type: object
                properties:
                  chats:
                    type: array
                    items:
                      type: object
                      properties:
                        _id:
                          type: string
                        name:
                          type: string
        '401':
          description: Unauthorized
  /ai/chat/{chatId}:
    get:
      tags:
      - Chat
      summary: Retrieve a specific chat session by ID
      security:
      - bearerAuth: []
      parameters:
      - in: path
        name: chatId
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Chat session details
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  name:
                    type: string
                  messages:
                    type: array
                    items:
                      $ref: '#/components/schemas/Message'
        '401':
          description: Unauthorized
        '404':
          description: Chat not found
    delete:
      tags:
      - Chat
      summary: Delete a specific chat session
      security:
      - bearerAuth: []
      parameters:
      - in: path
        name: chatId
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Chat session deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  chatId:
                    type: string
        '401':
          description: Unauthorized
        '404':
          description: Chat not found
  /ai/chat/{chatId}/rename:
    patch:
      tags:
      - Chat
      summary: Rename an existing chat session
      security:
      - bearerAuth: []
      parameters:
      - in: path
        name: chatId
        required: true
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - name
              properties:
                name:
                  type: string
                  description: New chat name
      responses:
        '200':
          description: Chat renamed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  name:
                    type: string
        '400':
          description: Invalid request (e.g., empty name)
        '401':
          description: Unauthorized
        '404':
          description: Chat not found
components:
  schemas:
    Message:
      type: object
      properties:
        role:
          type: string
        text:
          type: string
        files:
          type: array
          items:
            type: string
        status:
          type: string
        timestamp:
          type: string
          format: date-time
    SubscriptionStatus:
      type: object
      properties:
        plan:
          type: string
          enum:
          - free
          - premium
        active:
          type: boolean
        expiresAt:
          type: string
          format: date-time
    ResourceProcessingSummary:
      type: object
      properties:
        textExtracted:
          type: boolean
        imagesExtracted:
          type: boolean
        tablesExtracted:
          type: boolean
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
