name: CD to Azure VM

on:
  workflow_run:
    workflows: ["CI pipeline"]
    types:
      - completed
    branches:
      - main

jobs:
  push-config:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'push'
    name: Push config files to Azure VM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Rename nginx.conf
        run: cp frontend/nginx.conf nginx.conf

      - name: Push docker-compose.prod.yml and nginx.conf
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.AZURE_VM_SSH_PRIVATE_KEY }}
          source: "docker-compose.prod.yml,nginx.conf"
          target: /home/${{ secrets.AZURE_VM_USER }}

  push-secrets:
    needs: push-config
    name: Push secret files to Azure VM
    runs-on: ubuntu-latest

    steps:
      - name: Create .env file
        run: |
          echo "${{ secrets.BACKEND_ENV }}" > .env

      - name: Add firebaseKey.json
        run: |
          echo "${{ secrets.FIREBASE_KEY }}" > firebaseKey.json

      - name: Push secrets to Azure VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.AZURE_VM_SSH_PRIVATE_KEY }}
          source: .env,firebaseKey.json
          target: /home/${{ secrets.AZURE_VM_USER }}

  deploy:
    needs: push-secrets
    name: Deploy via Docker Compose
    runs-on: ubuntu-latest

    steps:
      - name: SSH & deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.AZURE_VM_SSH_PRIVATE_KEY }}
          script: |
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin <<< "${{ secrets.DOCKERHUB_TOKEN }}"
            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d --force-recreate --remove-orphans