name: CI pipeline

on:
  pull_request:
    branches: [ main ]
    types: [ reopened, synchronize, opened ]
  push:
    branches: [ main ]

env:
  IMAGE_BACKEND: ${{ secrets.DOCKERHUB_USERNAME }}/studybuddy-backend
  IMAGE_FRONTEND: ${{ secrets.DOCKERHUB_USERNAME }}/studybuddy-frontend

jobs:
  backend_pipeline:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env file
        run: |
          echo "${{ secrets.BACKEND_ENV }}" > .env

      - name: Create keys folder
        run: mkdir -p keys

      - name: Add firebaseKey.json to keys folder
        run: |
          echo "${{ secrets.FIREBASE_KEY }}" > keys/firebaseKey.json

      - name: Create .env.test file
        run: |
          echo "${{ secrets.BACKEND_ENV_TEST }}" > .env.test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Fix permissions for backend volume
        run: chmod -R 777 .

      - name: Build and test with Docker Compose
        run: |
          TAG=${{ github.sha }} docker compose \
            -f docker-compose.test.yml up \
            --build --abort-on-container-exit --exit-code-from test

      - name: Upload coverage report artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage-report
          path: backend/coverage_reports/coverage.xml

      - name: Log in to Docker Hub
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push backend image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_BACKEND }}:latest
            ${{ env.IMAGE_BACKEND }}:${{ github.sha }}

  frontend_pipeline:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Create .env file
        run: |
           echo "${{ secrets.FRONTEND_ENV }}" > .env

      - name: Run Unit Tests & Generate Coverage Report
        run: npm run coverage

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage-report
          path: frontend/coverage_reports/lcov.info

      - name: Log in to Docker Hub
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push frontend image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v3
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_FRONTEND }}:latest
            ${{ env.IMAGE_FRONTEND }}:${{ github.sha }}

  sonarcloud-scan:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    needs: [backend_pipeline, frontend_pipeline]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Download backend coverage
        uses: actions/download-artifact@v4
        with:
          name: backend-coverage-report
          path: backend/coverage_reports

      - name: Download frontend coverage
        uses: actions/download-artifact@v4
        with:
          name: frontend-coverage-report
          path: frontend/coverage_reports

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
